### ISSUE TITLE
Current Nuget is Pretty Old - 12/15/2017

### ISSUE THREAD

**Issue by ThxSkeleton** [luca-piccioni/OpenGL.Net#121]
*Current* version of the sample code no longer compiles using the nuget package 0.7.1.

 'Matrix4x4f' does not contain a definition for 'Ortho2D'
 error CS0019: Operator '*' cannot be applied to operands of type 'Matrix4x4f' and 'Matrix4x4f' 

Edit: Please push the latest copy to Nuget.

**Comment by luca-piccioni** [comment]
Yes, since Math has changed a lot, I've always procrastinated the nuget update. And Travis builds with VS2017 have stopped working for weird reasons. Now reverted to compile only on VS2015. 

I hope that next week I can find few hours to tag the next version.

**Comment by MarkWilds** [comment]
Did you manage to find any time for it?

**Comment by RUSshy** [comment]
any news on this ? ...

**Comment by luca-piccioni** [comment]
And finally, I've uploaded the nuget packages. Currently, they are in the validating phase, they will be available soon.

**Comment by RUSshy** [comment]
Thanks a lot !!!

**Comment by RUSshy** [comment]
I get this warning when using it in a .net core project

`` warning NU1701: Package 'OpenGL.Net 0.8.4' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.``

Why do i get the .net framework version instead of .net standard ?

**Comment by foobit** [comment]
@RUSshy I'm getting the same issue with *0.8.4* using a .net core project. That package version seems to be the core/standard assemblies.  Pulling nuget *0.7.1* does have the core/standard assemblies which I'm able to use in my project.  _However_ that does not fix your issue with the examples (if they havent been updated yet)

**Comment by RUSshy** [comment]
@foobit 
i think this is fixed by https://github.com/luca-piccioni/OpenGL.Net/pull/127 but i haven't tested i moved to simpler one file OpenGL binding

**Comment by foobit** [comment]
In #127 OpenGL.Net.nuspec does not have any file references for any netcoreapp2.0 or 3.0. I'll just work up pull request.
